import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Roboto font mui
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

// inter font mui joy
import "@fontsource/inter";

import Header from "./components/base/Header";
import { Container } from "@mui/material";
import Footer from "./components/base/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Container maxWidth="lg" sx={{ m: 1 }}>
          {children}
        </Container>
        <Footer />
      </body>
    </html>
  );
}
